# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGPAE', '0002_auto_20170224_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='periodo',
            field=models.IntegerField(default=0),
        ),
    ]
