# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGPAE', '0003_document_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='document',
            name='periodo',
            field=models.CharField(default='', max_length=10),
        ),
    ]
