# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIGPAE', '0004_auto_20170224_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(default='', max_length=512, null=True)),
                ('decanato', models.CharField(default='', max_length=512, null=True)),
                ('coordinacion_D1', models.CharField(default='', max_length=512, null=True)),
                ('coordinacion_D2', models.CharField(default='', max_length=512, null=True)),
                ('coordinacion_D3', models.CharField(default='', max_length=512, null=True)),
                ('division', models.CharField(default='', max_length=512, null=True)),
                ('departamento_D1', models.CharField(default='', max_length=512, null=True)),
                ('departamento_D2', models.CharField(default='', max_length=512, null=True)),
                ('departamento_D3', models.CharField(default='', max_length=512, null=True)),
                ('departamento_D4', models.CharField(default='', max_length=512, null=True)),
                ('codigo_asignatura', models.CharField(default='', max_length=512, null=True)),
                ('denominacion', models.CharField(default='', max_length=512, null=True)),
                ('periodo', models.CharField(default='', max_length=512, null=True)),
                ('anio', models.IntegerField(default=0, null=True)),
                ('horas_T', models.IntegerField(default=0, null=True)),
                ('horas_P', models.IntegerField(default=0, null=True)),
                ('horas_L', models.IntegerField(default=0, null=True)),
                ('num_creditos', models.IntegerField(default=0, null=True)),
                ('requisitos', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('estrategias_met', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('estrategias_ev', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('contenido', models.CharField(default='Sin seleccionar', max_length=512, null=True)),
                ('objetivos_generales', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('objetivos_especificos', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('fuentes_info', models.CharField(blank=True, default='', max_length=512, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='nombre',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='historial',
            name='docfile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIGPAE.Document'),
        ),
    ]
