# -*- coding: utf-8 -*-

cods = {
	'co':	'Cómputo Científico y Estadístico',
	'ep':	'Cursos en Cooperación',
	'dfm':	'Cursos en Cooperación',
	'et':	'Cursos en Cooperación',
	'ci':	'Dpto. Computación y Tecnología de la Información',
	'cib':	'Dpto. Computación y Tecnología de la Información',
	'bc':	'Dpto. de Biología Celular',
	'bcb':	'Dpto. de Biología Celular',
	'bo':	'Dpto. de Biología de Organismos',
	'bob':	'Dpto. de Biología de Organismos',
	'mt':	'Dpto. de Ciencia de los Materiales',
	'cmt':	'Dpto. de Ciencia de los Materiales',
	'gc':	'Dpto. de Ciencias de la Tierra',
	'ce':	'Dpto. de Ciencias Económicas y Administrativas',
	'cea':	'Dpto. de Ciencias Económicas y Administrativas',
	'cs':	'Dpto. de Ciencias Sociales',
	'csa':	'Dpto. de Ciencias Sociales',
	'csx':	'Dpto. de Ciencias Sociales',
	'csy':	'Dpto. de Ciencias Sociales',
	'csz':	'Dpto. de Ciencias Sociales',
	'egs':	'Dpto. de Ciencias Sociales',
	'cc':	'Dpto. de Ciencias y Tecnologías del Comportamiento',
	'cce':	'Dpto. de Ciencias y Tecnologías del Comportamiento',
	'ct':	'Dpto. de Conversión y Transporte de Energía',
	'cte':	'Dpto. de Conversión y Transporte de Energía',
	'da':	'Dpto. de Diseño Arquitectura y Artes Plásticas',
	'dap':	'Dpto. de Diseño Arquitectura y Artes Plásticas',
	'daa':	'Dpto. de Diseño Arquitectura y Artes Plásticas',
	'ec':	'Dpto. de Electrónica y Circuitos',
	'eyc':	'Dpto. de Electrónica y Circuitos',
	'ea':	'Dpto. de Estudios Ambientales',
	'ead':	'Dpto. de Estudios Ambientales',
	'ff':	'Dpto. de Filosofía',
	'fl':	'Dpto. de Filosofía',
	'fs':	'Dpto. de Física',
	'fsi':	'Dpto. de Física',
	'fis':	'Dpto. de Física',
	'fc':	'Dpto. de Formación General y Ciencias Básicas',
	'fca':	'Dpto. de Formación General y Ciencias Básicas',
	'fcb':	'Dpto. de Formación General y Ciencias Básicas',
	'fcc':	'Dpto. de Formación General y Ciencias Básicas',
	'fce':	'Dpto. de Formación General y Ciencias Básicas',
	'fcf':	'Dpto. de Formación General y Ciencias Básicas',
	'fcg':	'Dpto. de Formación General y Ciencias Básicas',
	'fch':	'Dpto. de Formación General y Ciencias Básicas',
	'fci':	'Dpto. de Formación General y Ciencias Básicas',
	'fcl':	'Dpto. de Formación General y Ciencias Básicas',
	'fcr':	'Dpto. de Formación General y Ciencias Básicas',
	'fcx':	'Dpto. de Formación General y Ciencias Básicas',
	'fcz':	'Dpto. de Formación General y Ciencias Básicas',
	'fcw':	'Dpto. de Formación General y Ciencias Básicas',
	'id':	'Dpto. de Idiomas',
	'idm':	'Dpto. de Idiomas',
	'll':	'Dpto. de Lengua y Literatura',
	'lla':	'Dpto. de Lengua y Literatura',
	'llb':	'Dpto. de Lengua y Literatura',
	'llc':	'Dpto. de Lengua y Literatura',
	'lle':	'Dpto. de Lengua y Literatura',
	'egl':	'Dpto. de Lengua y Literatura',
	'ma':	'Dpto. de Matemáticas Puras y Aplicadas',
	'mat':	'Dpto. de Matemáticas Puras y Aplicadas',
	'mc':	'Dpto. de Mecánica',
	'mec':	'Dpto. de Mecánica',
	'pl':	'Dpto. de Planificación Urbana',
	'plx':	'Dpto. de Planificación Urbana',
	'ply':	'Dpto. de Planificación Urbana',
	'ps':	'Dpto. de Procesos y Sistemas',
	'prs':	'Dpto. de Procesos y Sistemas',
	'qm':	'Dpto. de Química',
	'qim':	'Dpto. de Química',
	'pb':	'Dpto. de Tecnología de Procesos Biológicos y Bioquímicos',
	'ts':	'Dpto. de Tecnología de Servicios',
	'tsx':	'Dpto. de Tecnología de Servicios',
	'ti':	'Dpto. de Tecnología Industrial',
	'tf':	'Dpto. de Termodinámica y Fenómenos de Transformación',
	'tft':	'Dpto. de Termodinámica y Fenómenos de Transformación',
	'pg':	'Proyecto de Grado',
	'td':	'Tesis Doctoral',
	'teg':	'Traba Especial de Grado'
}