# -*- coding: utf-8 -*-

cods = {
	'co':	'Cómputo Científico y Estadístico',
	'ep':	'Cursos en Cooperación',
	'dfm':	'Cursos en Cooperación',
	'et':	'Cursos en Cooperación',
	'ci':	'Departamento de Computación y Tecnología de la Información',
	'cib':	'Departamento de Computación y Tecnología de la Información',
	'bc':	'Departamento de Biología Celular',
	'bcb':	'Departamento de Biología Celular',
	'bo':	'Departamento de Biología de Organismos',
	'bob':	'Departamento de Biología de Organismos',
	'mt':	'Departamento de Ciencia de los Materiales',
	'cmt':	'Departamento de Ciencia de los Materiales',
	'gc':	'Departamento de Ciencias de la Tierra',
	'ce':	'Departamento de Ciencias Económicas y Administrativas',
	'cea':	'Departamento de Ciencias Económicas y Administrativas',
	'cs':	'Departamento de Ciencias Sociales',
	'csa':	'Departamento de Ciencias Sociales',
	'csx':	'Departamento de Ciencias Sociales',
	'csy':	'Departamento de Ciencias Sociales',
	'csz':	'Departamento de Ciencias Sociales',
	'egs':	'Departamento de Ciencias Sociales',
	'cc':	'Departamento de Ciencias y Tecnologías del Comportamiento',
	'cce':	'Departamento de Ciencias y Tecnologías del Comportamiento',
	'ct':	'Departamento de Conversión y Transporte de Energía',
	'cte':	'Departamento de Conversión y Transporte de Energía',
	'da':	'Departamento de Diseño Arquitectura y Artes Plásticas',
	'dap':	'Departamento de Diseño Arquitectura y Artes Plásticas',
	'daa':	'Departamento de Diseño Arquitectura y Artes Plásticas',
	'ec':	'Departamento de Electrónica y Circuitos',
	'eyc':	'Departamento de Electrónica y Circuitos',
	'ea':	'Departamento de Estudios Ambientales',
	'ead':	'Departamento de Estudios Ambientales',
	'ff':	'Departamento de Filosofía',
	'fl':	'Departamento de Filosofía',
	'fs':	'Departamento de Física',
	'fsi':	'Departamento de Física',
	'fis':	'Departamento de Física',
	'fc':	'Departamento de Formación General y Ciencias Básicas',
	'fca':	'Departamento de Formación General y Ciencias Básicas',
	'fcb':	'Departamento de Formación General y Ciencias Básicas',
	'fcc':	'Departamento de Formación General y Ciencias Básicas',
	'fce':	'Departamento de Formación General y Ciencias Básicas',
	'fcf':	'Departamento de Formación General y Ciencias Básicas',
	'fcg':	'Departamento de Formación General y Ciencias Básicas',
	'fch':	'Departamento de Formación General y Ciencias Básicas',
	'fci':	'Departamento de Formación General y Ciencias Básicas',
	'fcl':	'Departamento de Formación General y Ciencias Básicas',
	'fcr':	'Departamento de Formación General y Ciencias Básicas',
	'fcx':	'Departamento de Formación General y Ciencias Básicas',
	'fcz':	'Departamento de Formación General y Ciencias Básicas',
	'fcw':	'Departamento de Formación General y Ciencias Básicas',
	'id':	'Departamento de Idiomas',
	'idm':	'Departamento de Idiomas',
	'll':	'Departamento de Lengua y Literatura',
	'lla':	'Departamento de Lengua y Literatura',
	'llb':	'Departamento de Lengua y Literatura',
	'llc':	'Departamento de Lengua y Literatura',
	'lle':	'Departamento de Lengua y Literatura',
	'egl':	'Departamento de Lengua y Literatura',
	'ma':	'Departamento de Matemáticas Puras y Aplicadas',
	'mat':	'Departamento de Matemáticas Puras y Aplicadas',
	'mc':	'Departamento de Mecánica',
	'mec':	'Departamento de Mecánica',
	'pl':	'Departamento de Planificación Urbana',
	'plx':	'Departamento de Planificación Urbana',
	'ply':	'Departamento de Planificación Urbana',
	'ps':	'Departamento de Procesos y Sistemas',
	'prs':	'Departamento de Procesos y Sistemas',
	'qm':	'Departamento de Química',
	'qim':	'Departamento de Química',
	'pb':	'Departamento de Tecnología de Procesos Biológicos y Bioquímicos',
	'ts':	'Departamento de Tecnología de Servicios',
	'tsx':	'Departamento de Tecnología de Servicios',
	'ti':	'Departamento de Tecnología Industrial',
	'tf':	'Departamento de Termodinámica y Fenómenos de Transformación',
	'tft':	'Departamento de Termodinámica y Fenómenos de Transformación',
	'pg':	'Proyecto de Grado',
	'td':	'Tesis Doctoral',
	'teg':	'Traba Especial de Grado'
}